language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - ruby-head
  - 1.8.7
  - ree
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - rbx-19mode
services: mongodb
