language: ruby
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.3.3
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - 1.8.7
  - ree
services: mongodb
matrix:
  allow_failures:
    - rvm: rbx-2
